/**
 * Scaffold — generate a minimal Playwright E2E starter for projects that
 * have no existing fixture.
 *
 * Decision tree:
 *   1. Read ProjectProfile (caller passes it in).
 *   2. If profile.stack.framework starts with "electron-" → defer message.
 *   3. Else write 5 files:
 *        - playwright.config.ts
 *        - e2e/smoke.spec.ts
 *        - e2e/README.md
 *        - package.json patch (test:e2e script + @playwright/test devDep)
 *        - .gitignore patch
 *   4. Refuse to overwrite unless force=true.
 *
 * Returns a structured result the CLI renders. The runner is a pure
 * file-writer; no I/O happens that the caller hasn't requested.
 */

import { existsSync, readFileSync } from "node:fs";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import type { ProjectProfile } from "../project-adapter/types.js";

export interface ScaffoldResult {
  filesWritten: string[];
  packageJsonPatched: boolean;
  gitignorePatched: boolean;
  electronDeferredTo: string | null;
  /** When true, scaffold refused to overwrite an existing file and the caller should --force. */
  refused: string[];
}

export interface ScaffoldOptions {
  force?: boolean;
}

const ELECTRON_DEFER = "Run `/electron-e2e-scaffold` to set up Playwright fixtures for the Electron target, then re-run `user-simulator scaffold`.";

export async function scaffoldProject(
  root: string,
  profile: ProjectProfile,
  opts: ScaffoldOptions = {},
): Promise<ScaffoldResult> {
  if (profile.stack.framework.startsWith("electron-")) {
    return { filesWritten: [], packageJsonPatched: false, gitignorePatched: false, electronDeferredTo: ELECTRON_DEFER, refused: [] };
  }

  const result: ScaffoldResult = {
    filesWritten: [],
    packageJsonPatched: false,
    gitignorePatched: false,
    electronDeferredTo: null,
    refused: [],
  };

  const files: Array<{ rel: string; content: string }> = [
    { rel: "playwright.config.ts", content: renderPlaywrightConfig(profile) },
    { rel: "e2e/smoke.spec.ts", content: renderSmokeSpec(profile) },
    { rel: "e2e/README.md", content: renderE2EReadme(profile) },
  ];

  for (const f of files) {
    const full = join(root, f.rel);
    if (existsSync(full) && !opts.force) {
      result.refused.push(f.rel);
      continue;
    }
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, f.content, "utf8");
    result.filesWritten.push(f.rel);
  }

  // Patch package.json
  const pkgPath = join(root, "package.json");
  if (existsSync(pkgPath)) {
    const pkg = JSON.parse(await readFile(pkgPath, "utf8")) as Record<string, unknown>;
    const before = JSON.stringify(pkg);
    pkg.scripts = { ...(pkg.scripts as Record<string, string> | undefined ?? {}), "test:e2e": "playwright test" };
    pkg.devDependencies = { ...(pkg.devDependencies as Record<string, string> | undefined ?? {}), "@playwright/test": "^1.61.1" };
    const after = JSON.stringify(pkg, null, 2);
    if (before !== after) {
      await writeFile(pkgPath, after, "utf8");
      result.packageJsonPatched = true;
    }
  }

  // Patch .gitignore
  const giPath = join(root, ".gitignore");
  const additions = ["playwright-report/", "test-results/", "playwright/.cache/"];
  let existing = "";
  if (existsSync(giPath)) {
    existing = readFileSync(giPath, "utf8");
  }
  const missing = additions.filter((a) => !existing.includes(a));
  if (missing.length > 0) {
    const newContent = (existing ? existing.replace(/\s*$/, "\n") : "") + missing.join("\n") + "\n";
    await writeFile(giPath, newContent, "utf8");
    result.gitignorePatched = true;
  }

  return result;
}

function renderPlaywrightConfig(p: ProjectProfile): string {
  const port = p.dev.port;
  return `// Generated by user-simulator v4 scaffold
// To run: npx playwright test
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./e2e",
  timeout: 30_000,
  fullyParallel: true,
  reporter: [["list"], ["html", { open: "never" }]],
  use: {
    baseURL: process.env.E2E_BASE_URL ?? "http://localhost:${port}",
    trace: "on-first-retry",
    screenshot: "only-on-failure",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
});
`;
}

function renderSmokeSpec(p: ProjectProfile): string {
  const selectorLine = p.smoke.selector
    ? `  await page.locator(${JSON.stringify(p.smoke.selector)}).click();\n`
    : "";
  return `// Generated by user-simulator v4 scaffold
import { test, expect } from "@playwright/test";

test("smoke: home renders without console errors", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(e.message));
  page.on("console", (m) => {
    if (m.type() === "error") errors.push(m.text());
  });

  await page.goto("/");
${selectorLine}
  await expect(page).toHaveTitle(/.+/);
  expect(errors).toEqual([]);
});
`;
}

function renderE2EReadme(p: ProjectProfile): string {
  return `# E2E Tests

Generated by \`user-simulator scaffold\` (v4) because no Playwright fixture was
detected in this project (stack: \`${p.stack.framework}\`, port: \`${p.dev.port}\`).

## Run

\`\`\`bash
npx playwright test
\`\`\`

The first run downloads Chromium (~150MB) into your local Playwright cache.

## What this gives you

A single smoke test that loads the home page, listens for \`pageerror\` and
\`console.error\`, and asserts the page has a title. Extend \`e2e/smoke.spec.ts\`
or add more spec files alongside it.

## How user-simulator uses these

\`user-simulator\` itself does **not** run these specs during a v1.x run
(its run-web / run-electron drivers only make the target reachable and then
drive via AI action-client). This scaffold is **developer-facing** — you run
it manually, fix the smoke, then use user-simulator's AI-driven simulation
on top. Closing the loop (letting user-simulator invoke these specs
automatically) is a follow-up.
`;
}