/**
 * Report writer — Markdown + JSON outputs.
 *
 * Follows the standard exploratory-testing report shape: severity summary
 * table, per-bug evidence (screenshots, repro steps, detector trail),
 * candidates list, optional API assertion results, and explicit
 * limits-of-this-run disclaimer.
 */

import type { Bug } from "../common/contracts.js";
import type { ApiAssertionResult } from "../api-verify/contracts.js";

export interface ReportInput {
  run_id: string;
  confirmed: Bug[];
  candidates: Bug[];
  artifact_root: string;
  /** v4: optional API assertion results from verify-api subcommand. */
  api_results?: ApiAssertionResult[];
}

export function renderMarkdownReport(input: ReportInput): string {
  const { run_id, confirmed, candidates, artifact_root, api_results } = input;
  const lines: string[] = [];

  lines.push(`# User Simulator Report — ${run_id}`);
  lines.push("");
  lines.push(`Generated by user-simulator v4.0.0. Artifacts under \`${artifact_root}\`.`);
  lines.push("");

  const counts = countBySeverity(confirmed);
  lines.push("## Summary");
  lines.push("");
  lines.push(`| Severity | Confirmed | Candidates |`);
  lines.push(`|---|---:|---:|`);
  for (const s of ["S0", "S1", "S2", "S3"] as const) {
    lines.push(`| ${s} | ${counts.confirmed[s] ?? 0} | ${counts.candidates[s] ?? 0} |`);
  }
  lines.push(`| **Total** | **${confirmed.length}** | **${candidates.length}** |`);
  lines.push("");

  if (confirmed.length > 0) {
    lines.push("## Confirmed Bugs");
    lines.push("");
    for (const b of confirmed) {
      lines.push(...renderBugBlock(b));
      lines.push("");
    }
  }

  if (candidates.length > 0) {
    lines.push("## Candidates (vision-only, not promoted)");
    lines.push("");
    for (const b of candidates) {
      lines.push(...renderBugBlock(b));
      lines.push("");
    }
  }

  if (api_results && api_results.length > 0) {
    lines.push("## API Assertions (v4)");
    lines.push("");
    lines.push(`| ID | Status | Duration | Message |`);
    lines.push(`|---|---|---:|---|`);
    for (const r of api_results) {
      const icon = r.status === "pass" ? "✓" : r.status === "fail" ? "✗" : "?";
      lines.push(`| ${r.assertion_id} | ${icon} ${r.status} | ${r.duration_ms}ms | ${r.message.replace(/\|/g, "\\|")} |`);
    }
    lines.push("");
  }

  lines.push("## Limits of this run");
  lines.push("");
  lines.push("- Single-run; not a multi-seed average. Free-exploration paths may differ.");
  lines.push("- Vision/UX findings require independent verification.");
  lines.push("- Performance data is a single sample — not a regression baseline.");
  lines.push("- Race conditions, memory leaks, and platform-specific issues are NOT covered.");
  lines.push("- API assertions exercise one round each; auth-protected endpoints need --api-header.");
  lines.push("");

  return lines.join("\n");
}

function renderBugBlock(b: Bug): string[] {
  const loc = b.location
    ? [b.location.route && `route: \`${b.location.route}\``, b.location.window && `window: \`${b.location.window}\``, b.location.element && `element: \`${b.location.element}\``]
        .filter(Boolean).join(" · ")
    : "(no location)";
  const detectors = b.detectors?.length ? b.detectors.join(", ") : "(none)";
  const evidence = b.evidence?.screenshots?.length
    ? b.evidence.screenshots.map((p) => `\`${p}\``).join(", ")
    : "—";
  return [
    `### ${b.severity} — ${b.title}`,
    ``,
    `- **bug_id**: \`${b.bug_id}\``,
    `- **fingerprint**: \`${b.fingerprint}\``,
    `- **type**: ${b.type}`,
    `- **confidence**: ${b.confidence}`,
    `- **location**: ${loc}`,
    b.expected !== undefined ? `- **expected**: ${b.expected}` : "",
    b.actual !== undefined ? `- **actual**: ${b.actual}` : "",
    `- **detectors**: ${detectors}`,
    `- **screenshots**: ${evidence}`,
    ...(b.reproduction_steps && b.reproduction_steps.length > 0
      ? [`- **reproduction**:`, ...b.reproduction_steps.map((s) => `  - ${s}`)]
      : []),
  ].filter(Boolean);
}

function countBySeverity(bugs: Bug[]): Record<"confirmed" | "candidates", Record<string, number>> {
  const confirmed: Record<string, number> = { S0: 0, S1: 0, S2: 0, S3: 0 };
  const candidates: Record<string, number> = { S0: 0, S1: 0, S2: 0, S3: 0 };
  for (const b of bugs) {
    if (b.candidate) candidates[b.severity] = (candidates[b.severity] ?? 0) + 1;
    else confirmed[b.severity] = (confirmed[b.severity] ?? 0) + 1;
  }
  return { confirmed, candidates };
}